/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DefensePoolInterface extends Interface {
    getFunction(nameOrSignature: "authorizedAgent" | "deposit" | "executeDefense"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DefenseExecuted" | "FundsDeposited"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizedAgent', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeDefense', values: [BytesLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'authorizedAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeDefense', data: BytesLike): Result;
  }

  
    export namespace DefenseExecutedEvent {
      export type InputTuple = [targetToken: AddressLike, amount: BigNumberish];
      export type OutputTuple = [targetToken: string, amount: bigint];
      export interface OutputObject {targetToken: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DefensePool extends BaseContract {
    
    connect(runner?: ContractRunner | null): DefensePool;
    waitForDeployment(): Promise<this>;

    interface: DefensePoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedAgent: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    executeDefense: TypedContractMethod<
      [signature: BytesLike, targetToken: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedAgent'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'executeDefense'): TypedContractMethod<
      [signature: BytesLike, targetToken: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DefenseExecuted'): TypedContractEvent<DefenseExecutedEvent.InputTuple, DefenseExecutedEvent.OutputTuple, DefenseExecutedEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;

    filters: {
      
      'DefenseExecuted(address,uint256)': TypedContractEvent<DefenseExecutedEvent.InputTuple, DefenseExecutedEvent.OutputTuple, DefenseExecutedEvent.OutputObject>;
      DefenseExecuted: TypedContractEvent<DefenseExecutedEvent.InputTuple, DefenseExecutedEvent.OutputTuple, DefenseExecutedEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    
    };
  }